manifest:
  remotes:
    - name: pagedpenguin251
      url-base: https://github.com/pagedpenguin251
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: pagedpenguin251
      revision: plover-hid
      import: app/west.yml
  self:
    path: config
