manifest:
  remotes:
    - name: pagedpenguin251
      url-base: https://github.com/pagedpenguin251
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: pagedpenguin251
      revision: plover
      import: app/west.yml
    # include corne with dongle pro_micro and xiao compatible
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
      # - name: zmk-nice-oled
      # remote: mctechnology17
      # revision: main
  self:
    path: config
