manifest:
  remotes:
    - name: pagedpenguin251
      url-base: https://github.com/pagedpenguin251
  projects:
    - name: zmk
      remote: pagedpenguin251
      revision: plover
      import: app/west.yml
  self:
    path: config
