manifest:
  remotes:
    - name: phzmk
      url-base: https://github.com/phuertay
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: phzmk
      revision: main
      import: app/west.yml
    - name: zmk-antecedent-morph
      remote: phzmk
      revision: v1
  self:
    path: config
